### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by andrewbuie** [atom/editor-stats#11] opened 2015-01-25 09:00 UTC
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:55:11)
EditorStatsView.detach (/Users/Andrew/.atom/packages/editor-stats/lib/editor-stats-view.coffee:103:9)
```

**Comment by izuzak** [comment] 2015-01-25 18:54
Dupe of https://github.com/atom/editor-stats/issues/8

**Closed by izuzak** 2015-01-25 18:54 UTC
